### ISSUE TITLE
 Missing CONTRIBUTING.md File in Repository

### ISSUE THREAD

**Issue by anshgautam-github** [Open-Source-Chandigarh/Euphoria-Check#44]
repository currently lacks a CONTRIBUTING.md file, which is an important resource for guiding potential contributors on how to engage with the project effectively. A CONTRIBUTING.md file outlines the contribution guidelines, coding standards, and procedures for submitting pull requests, thus streamlining the contribution process and ensuring consistency across contributions.

Kindly, assign me under GSSOC 2024

**Comment by KUMUD-TECH** [comment]
I would like to work on this CONTRIBUTING.md file.
This should be the first issue that needs to resolve.
so that contributers can contribute to your repository in a right manner.
you can also see who has contributed to your repository and about them.
you can see who is more experienced so that you can assign issues in future.

please assign this issue to me.

**Comment by Aryainguz** [comment]
Go ahead on this @anshgautam-github

**Comment by anshgautam-github** [comment]
@Aryainguz  thank you !
I would like to know is the GSSOC label matters for the contribution towards it ?
